### PR TITLE
Add PizzaService classes to test

### PR DESCRIPTION
**Pull request by perrycbrown**
Hi Ishaq and Kiran,

I'm creating this pull request to illustrate how I created a branch off the master branch for our pizza project (locally in my Macintosh), added my changes and updates to that new branch, then pushed my new branch back to github.

Then I created a pull request on github so you would be notified about my desire to merge my new branch back into the master branch. 

Pull requests are not always necessary; you can always merge your local test branches directly back into the master branch on your computer, then push the master branch back to github for us to share. But thought it might be helpful to illustrate the pull request process also.

And do forgive me if you knew all of this already. My apologies :-)

### CODE REVIEW

**Comment by ishaqu** [comment]
Hey Kiran,

Are you available tomo morning to meet ?

**Comment by vvenuturimilli** [comment]
Yup let me know the time and place

**Comment by ishaqu** [comment]
Perry,

Pick a place that works for you and we can meet at 10..

**Comment by ada81** [comment]
Hi, please remove me from the email recipient list when possible. Thanks

Regards,
Adanna

**Pull request merged**
